#!/bin/bash

# 脚本中使用的环境变量
export WPath_DailyPath="${HOME}/wang/12.工作日志/3.uos/1.日报/2022"
export WPath_ShellTmp="${HOME}/.cache/wang.tmp"
export WPath_BashWangDir="$HOME/wang/01.work-ln/wbash/wang"
export WPath_WorkDir="${HOME}/wang/01.work-ln"
export WPath_NoteDir="${HOME}/wang/04.note.dir"
export WPath_wallpapersDir="${HOME}/wang/30.file/20.wallpper-pc"
export WPath_WToolsDir="${HOME}/wang/02.code/git-my/wtools"
export WPath_AppImage="${HOME}/wang/31.book-software/AppImage"
export WPath_Private="${HOME}/wang/11.private"
export WPath_wbash="${HOME}/wang/02.code/git-my/wbash"

# Tips: 
#	update-ln-file 		中仍然使用了一些路径
# 	wbashrc_private		中有些路径也需要修改
source ~/wang/30.file/wbashrc_private

alias ll="ls -alh"

alias kvm="sudo virt-manager"
alias wework="uos-open-desktopfile /opt/apps/com.qq.weixin.work.deepin/entries/applications/com.qq.weixin.work.deepin.desktop"
alias wechat="uos-open-desktopfile /opt/apps/com.qq.weixin.deepin/entries/applications/com.qq.weixin.deepin.desktop"
alias qq="uos-open-desktopfile /opt/apps/com.qq.im.deepin/entries/applications/com.qq.im.deepin.desktop"
alias sunflower="uos-open-desktopfile /opt/apps/com.oray.sunlogin.client/entries/applications/com.oray.sunlogin.client.desktop"

alias wtools="uos-open-desktopfile /usr/share/applications/wtools.desktop "
alias todo="gedit ~/wang/01.work-ln/todo.txt"

alias adjust-brightness="xrandr --output HDMI-2 --brightness 0.6"
alias open=xdg-open
alias open-test="gedit ~/wang/01.work-ln/wbash/example/test.sh"
alias open-weblink="gedit ~/wang/01.work-ln/weblink-链接.md"
alias google-bookmarket="cat \"$(find ~/.config -name Bookmarks)\" | grep -v sync_metadata"

# 环境变量
# go env
export GOPATH=/home/wangbin/go:/usr/share/gocode
# export GOPROXY=https://goproxy.cn
export PATH=$PATH:$WPath_wbash/uos-func
export PATH=$PATH:$WPath_wbash/wang
export PATH=$PATH:$WPath_wbash/example
export PATH=$PATH:~/zwork/bin

# 设置contab编辑器为vim
# export EDITOR=/usr/bin/vim




