#!/bin/bash

if [ "-h" == "$1" ] || [ "" == "$1" ];then
    echo "uos-no-password [true/false]"
    return
fi

sudo dbus-send --system --type=method_call --print-reply --dest=com.deepin.daemon.Accounts /com/deepin/daemon/Accounts/User1000 com.deepin.daemon.Accounts.User.EnableNoPasswdLogin boolean:$1
