#!/bin/bash

if [ "-h" == "$1" ] || [ "" == "$1" ];then
    echo "uos-auto-login [true/false]"
    exit 0
fi

# knowledge
sudo dbus-send --system --type=method_call --print-reply   --dest=com.deepin.daemon.Accounts /com/deepin/daemon/Accounts/User1000 com.deepin.daemon.Accounts.User.SetAutomaticLogin boolean:$1
