#!/bin/bash

if [ "-h" == "$1" ] || [ "" == "$1" ];then
    echo "uos-vpn [true/false]"
    exit 1
fi

if $1 ;then
    echo '开启系统代理'
    gsettings set org.gnome.system.proxy use-same-proxy true
    gsettings set org.gnome.system.proxy mode 'auto'
    gsettings set org.gnome.system.proxy autoconfig-url 'https://it.uniontech.com/proxy/proxy.pac'
else
    echo '关闭系统代理'
    gsettings set org.gnome.system.proxy use-same-proxy false
fi
