#!/bin/bash
# 打开月度工作日志文件

if [ "" == "$1" ] || [ "-h" == "$1" ] || [ "--h" == "$1" ] || [ "-help" == "$1" ] || [ "--help" == "$1" ];then
    echo '请输入月份'
    exit 1
fi

path=$WPath_DailyPath
for file in `ls $path`
do
    idx=$(echo $file | cut -d '-' -f 1 | tr -d 0)
    echo $file "[ $1 -eq $idx ]"
    if [[ $1 -eq $idx ]] ; then
        echo "$path/$file"
        gedit "$path/$file"
    fi
done

