#!/bin/bash
# 打开月度工作日志文件

if [ "" == "$1" ] || [ "-h" == "$1" ] || [ "--h" == "$1" ] || [ "-help" == "$1" ] || [ "--help" == "$1" ];then
    echo '请输入月份'
    exit 1
fi

dailypath='/home/wangbin/wang/09.工作日志/3.uos/1.日报/2022'
ls $dailypath
for file in `ls $dailypath`
do
    idx=$(echo $file | cut -d '-' -f 1 | tr -d 0)
    echo $file "[ $1 -eq $idx ]"
    if [[ $1 -eq $idx ]] ; then
        echo "$dailypath/$file"
        gedit "$dailypath/$file"
    fi
done

