#!/bin/bash
#set -x

#if [ "" == "$1" ] || [ "-h" == "$1" ] || [ "--h" == "$1" ] || [ "-help" == "$1" ] || [ "--help" == "$1" ];then
#    echo ''
#fi

declare -A interfacesMap

while read -r line ;
do
    key=`echo $line | cut -d ' ' -f 1`
    if [ "$key" != "signal" ] && [ "$key" != "method" ] ;then
        continue
    fi

    interface=""
    member=""
    for e in $line
    do
        if [[ "$e" =~ "interface=" ]];then
            interface=`echo $e | awk -F 'interface=' '{print $2}' |cut -d ';' -f 1`
        fi
        if [[ "$e" =~ "member=" ]];then
            member=`echo $e | awk -F 'member=' '{print $2}' |cut -d ';' -f 1`
        fi
    done

  if [ "$interface" == "com.deepin.api.XEventMonitor" ] || [ "$interface" == "com.deepin.daemon.Gesture" ] ||
      [ "$interface" == "org.freedesktop.DBus" ] || [ "$interface" == "" ]
  then
    continue
  fi

    if [[ "${interfacesMap[$interface]}" != "$member" ]] ; then
        # 防止一个信号反复的输出 比如 interface=com.deepin.api.XEventMonitor member=CursorMove
        echo "$key: interface=$interface member=$member"
        echo "       "$line
    fi
    interfacesMap[$interface]=$member
done


