#!/bin/bash

if [ $# -eq 0 ];then
    echo "${0##*/} k1 k2 k3   关键行必须同时满足n个key  且egrep本身体同时支持'A|B'"
    exit
fi

tmpfile=$WPath_ShellTmp
cat /dev/null > $tmpfile

paths=`bash $WPath_BashWangDir/knowledge-dir`

for s_dir in $paths ; do
    egrep -R -n -E "$1" "$s_dir" >> $tmpfile
done

for arg in $*
do
    if [ $arg == $1 ];then
    	# 过滤掉k1
        continue
    fi

    echo "$(egrep $arg $tmpfile)" > $tmpfile     # echo egrep的结果 保留换行
done

# 格式化输出
if [ $(cat $tmpfile | wc -l) -eq 1 ] ;then
    filename=`cat $tmpfile |cut -d ':' -f 1`
    if [ "$filename" == "" ]; then
        echo "请减少关键字"
    else
        cat $tmpfile
    fi

else
    cat $tmpfile
fi

