#!/bin/bash

# 获取我的笔记文件夹 排除一些指定文件夹
wworkdir=$(readlink -f $WPath_WorkDir | xargs echo)

for e in `ls $wworkdir`
do
    path=$wworkdir/$e
    # 排除文件 保留文件夹
    if [[ ! -d $path ]];then
        continue
    fi

    if [[ $path =~ "zbash" ]] ;then
        continue
    fi

     echo $path
done
