#!/bin/bash

# 重命名当前文件夹中的 文本文件
# 1) 如果是数子开头，并且数字后是 '.'
#		数字是2位数，跟新 '.' 之前的索引
#		数字是3位数，跳过
# 2) 索引大于99，退出脚本

idx=1
for name in `ls -F | grep -v '/$'`
do
	sindex=$(echo $idx | awk '{printf("%02d\n",$0)}')
	echo "index: $sindex"
	newname=""

	if [[ $name =~ ^[0-9][0-9]\. ]] || [[ $name =~ ^[0-9]\. ]];then
		# .号前面是 1位或者2位数字的
		# ${name#*.}  从左向右第一个 '.' 出现之后的字符串
		newname=$sindex.${name#*.}
		echo "newname 1 : $newname"
	elif [[ $name =~ ^[0-9][0-9][0-9]\. ]];then
		echo "ginore $name"
		continue
	else
		newname=$sindex.$name
		echo "newname 2 : $newname"
	fi
	
	if [ "$name" != "$newname" ];then
		mv $name $newname
		echo "mv $name $newname"
	fi
	
	#echo $idx
	let idx++
	
	if [ $idx -eq 100 ];then
		tip="File Index is greater than 99, break"
		echo -e "\033[31m $tip \033[0m"
		break
	fi
done
