#!/bin/bash

if  [ "" == "$1" ] || [ "-h" == "$1" ] || [ "" == "$1" ];then
    # 替换opml文件中的http头 https:/*/  为参数1
    echo "${0##*/} [127.0.0.1:1200]"
    exit
fi

tmpip=`egrep "/bilibili/user/video" ~/Desktop/rss订阅.opml |awk -F "/bilibili/user/video" '{print $1}' |awk -F "http://" '{print $2}'`
ip=`echo $tmpip | cut -d ' ' -f 1`

sed -i "s/$ip/$1/g" $WPath_AppImage/rss/rss订阅.opml
echo sed -i "s/$ip/$1/g" $WPath_AppImage/rss/rss订阅.opml
