#!/bin/bash

pixpath=$WPath_wallpapersDir
sysWallpaper=/usr/share/wallpapers/deepin

sudo rm -rf $sysWallpaper/*
for pathname in `find $pixpath` ;
do
	if [ -d $pathname ];then
		continue
	fi
	echo "cp $pathname $sysWallpaper/"
    sudo cp "'$pathname'" $sysWallpaper/
done

